apiVersion: v1
kind: Service
metadata:
  name: portfolio-django-service
  namespace: pdf-api
  labels:
    app: portfolio-django
spec:
  selector:
    app: portfolio-django
  ports:
  - port: 8002
    targetPort: 8002
    name: http