apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: pdf-api
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "mYirh9A1bCFFd3hc3AeBpJ-VJDYl8n9s"
  DEBUG: "False"
  ALLOWED_HOSTS: "saturnin.bm-backend.ovh"
  DATABASE_URL: "sqlite:////app/db.sqlite3"
  CLOUDINARY_CLOUD_NAME: "dhc0gpzwo"
  CLOUDINARY_API_KEY: "114576984547544"
  CLOUDINARY_API_SECRET: "a_completer"
  EMAIL_PASSWORD: "a_completer"